# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenLive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenLive
  pod 'AgoraRtcEngine_iOS', '3.4.1'

  target 'OpenLive-Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
